---
title: "Homework 4"
output:
  html_document:
    df_print: paged
---

```{r}
library(datasets)
library(dplyr)
library(ggplot2)
?ChickWeight
print(ChickWeight)
```

1.
```{r}
weight0 <- ChickWeight %>%
  group_by(Diet) %>%
  summarize(avg = mean(weight), sd= sd(weight))
  

print(weight0)
```
2.
```{r}
complete <- ChickWeight %>%
  group_by(Chick) %>%
  tally(name="num_measurements") %>%
  filter(num_measurements > 11)


print(head(complete,3))

```

3.
```{r}

# only add if in previous df 
foo <- list()

print((nrow(ChickWeight)))
for (row in 1:nrow(ChickWeight)) {
  print(ChickWeight[row,]$Chick)
  if (ChickWeight[row,]$Chick %in% complete$Chick){
    append(foo,ChickWeight[row,])
  }
  
}
data.frame(foo)
#weightgain <- ChickWeight %>%
  #group_by(Chick) %>%
  #mutate(zerow = weight[Time == 0]) %>%
  #mutate(weightgain = weight - zerow) %>%
 # select(-zerow) 
#head(complete, 3)
  
```
4.
```{r}
ChickWeight[3] <- lapply(ChickWeight[3], as.numeric)

foo <- ChickWeight %>%
filter(df, ChickWeight$Chick %in% complete$Chick)
```

